  superuser-secret:
    secretName: superuser-secret
    secretKey: username
    passwordSecretKey: password
    

  giteadatabase:
    secretName: giteadatabase
    userSecretKey: username
    passwordSecretKey: password
    connectionStringSecretKey: connectionString




