apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true 

  superuserSecret:
    name: superuser-secret

  backup:
    barmanObjectStore:
      destinationPath: s3://pg-backup-2
      endpointURL: https://eu2.contabostorage.com
      s3Credentials:
        accessKeyId:
          name: contabocredentials
          key: username
        secretAccessKey:
          name: contabocredentials
          key: password
    retentionPolicy: "30d"

  bootstrap:
    recovery:
      source: postgres


  externalClusters:
    - name: postgres
      barmanObjectStore:
        destinationPath: s3://pg-backup-test
        endpointURL: https://eu2.contabostorage.com
        s3Credentials:
          accessKeyId:
            name: contabocredentials
            key: username
          secretAccessKey:
            name: contabocredentials
            key: password
