commonLabels:
  helmfile-bundle: "basic:0.0.1"


repositories:
 - name: mittwald
   url: https://helm.mittwald.de
 - name: grafana
   url: https://grafana.github.io/helm-charts
 - name: bitnami
   url: https://charts.bitnami.com/bitnami
 - name: jetstack
   url: https://charts.jetstack.io

releases:
- name: cilium
  namespace: kube-system
  chart: ../../charts/cilium
  condition: cilium.enabled
  values:
    - &env env-magic.gotmpl # use a YAML anchor for DRYness

- name: postgres-operator
  condition: postgres.enabled
  namespace: postgres
  chart: ../../charts/cloudnative-pg
  values:
    - *env # reference the anchor
  wait: true
  waitForJobs: true

- name: database-cluster
  condition: postgres.enabled
  disableValidation: true
  namespace: postgres
  chart: ../../charts/database-cluster
  values:
    - *env # reference the anchor
  needs: 
    - postgres-operator
  waitForJobs: true

- name: replicator
  namespace: kube-system
  chart: mittwald/kubernetes-replicator
  values:
    - *env # reference the anchor
- name: prometheus
  disableValidation: true
  condition: monitoring.enabled
  namespace: monitoring
  chart: ../../charts/kube-prometheus
  values:
    - *env # reference the anchor
  wait: true
- name: grafana-operator
  condition: monitoring.enabled
  disableValidation: true
  namespace: monitoring
  chart: ../../charts/grafana-operator
  disableOpenAPIValidation: true
  values:
    - *env # reference the anchor
- name: loki
  condition: monitoring.enabled
  namespace: monitoring
  disableValidation: true
  chart: ../../charts/grafana-loki
  values:
    - *env # reference the anchor
- name: cert-manager
  condition: cert-manager.enabled
  disableValidation: true
  namespace: cert-manager
  chart: ../../charts/cert-manager
  values:
    - *env # reference the anchor
  
- name: cert-issuers
  condition: cert-manager.enabled
  namespace: cert-manager
  chart: ../../charts/cert-issuers 
  values:
    - *env # reference the anchor
  needs: 
    - cert-manager

- name: vaultwarden-database
  condition: vaultwarden.enabled
  namespace: postgres
  chart: ../../charts/database-vaultwarden
  values:
    - *env # reference the anchor
  needs: 
    - database-cluster

- name: vaultwarden
  condition: vaultwarden.enabled
  namespace: vaultwarden
  chart: ../../charts/vaultwarden
  values:
    - *env # reference the anchor
  needs: 
    - postgres/vaultwarden-database

- name: gitea-database
  condition: gitea.enabled
  namespace: postgres
  chart: ../../charts/database-gitea
  values:
    - *env # reference the anchor
  needs: 
    - database-cluster    

- name: gitea
  condition: gitea.enabled
  namespace: gitea
  chart: ../../charts/gitea
  values:
    - *env # reference the anchor  
  needs: 
    - postgres/gitea-database



environments:
  default:
    values:
      - environments/default/values.yaml
  local:
    values: # apply default first, then prod
      - environments/default/values.yaml 
      - environments/local/values.yaml
