apiVersion: v1
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=

kind: Secret
metadata:
  name: postgres 
type: kubernetes.io/basic-auth

---

apiVersion: v1
data:
  username: dGVzdA==
  password: dGVzdGFy
  connectionString: cG9zdGdyZXNxbDovL3Rlc3Q6dGVzdGFyQHBvc3RncmVzLXJ3LnBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvcmVnaXN0cnk=

kind: Secret
metadata:
  name: vaultwarden-postgres

  annotations:
    replicator.v1.mittwald.de/replicate-to: "vaultwarden"

type: kubernetes.io/basic-auth



