apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasources:
    - name: loki
      type: loki
      access: proxy
      url: {{ .Values.lokidatasource }}
      isDefault: true
      jsonData:
        'tlsSkipVerify': true
        'timeInterval': "5s"
      editable: true
  name: loki
---
