apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      isDefault: false
      jsonData:
        'tlsSkipVerify': true
        'timeInterval': "5s"
      editable: true
  name: prometheus
---
