apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: {{ .Values.prometheusdatasource }}
      isDefault: false
      jsonData:
        'tlsSkipVerify': true
        'timeInterval': "5s"
      editable: true
  name: prometheus
---
