apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: {{ ternary (randAlphaNum 10) .Values.admin.password (empty .Values.admin.password) | b64enc | quote }}
  GF_SECURITY_ADMIN_USER: {{ ternary (randAlphaNum 10) .Values.admin.user (empty .Values.admin.user) | b64enc | quote }}
kind: Secret
metadata:
  name: grafana
type: Opaque
