apiVersion: v1
data:
  username: YXBw
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth

---
apiVersion: v1
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: superuser-secret
type: kubernetes.io/basic-auth

---
apiVersion: v1
data:
  username: NWJlNTMzMDZiZmI0ZWU4ODk0ZGM5NTE1MWMxN2IzNDk=
  password: OWI0NGM0NzZlNGUwYmE1NGU5MWY5Njc1OWY2OTk3Yzk=
kind: Secret
metadata:
  name: contabocredentials
#type: kubernetes.io/basic-auth


