apiVersion: v2
appVersion: 1.27.0
description: Unofficial Bitwarden compatible server written in Rust
home: https://github.com/dani-garcia/vaultwarden - bitwarden - bitwarden_rs - password
  - vaultwarden
icon: https://upload.wikimedia.org/wikipedia/commons/0/03/Bitwarden_Logo.png
maintainers:
- email: silvio@gissilabs.com
  name: Silvio Gissi
name: vaultwarden
sources:
- https://github.com/dani-garcia/vaultwarden
type: application
version: 1.0.0
