# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: {{ .Values.replicas | default 3 }}

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: {{ (((.Values.resources).storage).request | default "1Gi" }} 

  monitoring:
    enablePodMonitor: true    


#  resources:
#    storage:
#      request: 1Gi
#  replicas: 3
