

apiVersion: v1
data:
  username: dGVzdA==
  password: dGVzdGFy
  connectionString: cG9zdGdyZXNxbDovL3Rlc3Q6dGVzdGFyQHBvc3RncmVzLXJ3LnBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvcmVnaXN0cnk=

kind: Secret
metadata:
  name: giteadatabase

  annotations:
    replicator.v1.mittwald.de/replicate-to: "gitea"

type: kubernetes.io/basic-auth





